<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Subscriber.Sample</RootNamespace>
    <AssemblyName>Subscriber.Sample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MessageBroadcast.Client\MessageBroadcast.Client.csproj" />
  </ItemGroup>

</Project>